### ISSUE TITLE
Can't locate List\UtilsBy.pm in @INC (@INC contains: .)

### ISSUE THREAD

**Issue by atalec** [fieldmuseum/EMu-scripts#1]
I attempted to run this script on our EMu server today, and received an error message.

Can't locate List\UtilsBy.pm in @INC (@INC contains: .)
BEGIN failed--compliation aborted at ./convertSchemaToExcel.pl line 15

**Comment by magpiedin** [comment]
It sounds like the "List::UtilsBy" perl module might not be installed 
(similar to the [ReadMe's 2nd "troubleshooting" issue](https://github.com/fieldmuseum/EMu-scripts/blob/master/Schema/README.md) )

two suggestions:
- any luck if you try `sudo cpan install List::UtilsBy` ?
(if you don't want to try that directly on your live server, you could copy your schema.pl file to a separate enviro, setup perl, & run the script there)

- this details some other things to check: https://perlmaven.com/cant-locate-in-inc

**Comment by atalec** [comment]
Thank you.

I am in the process of building a separate linux instance to test this out.

**Comment by magpiedin** [comment]
Sounds good -- and the version of perl might help/hinder (perl v5.18.2 worked for us here)

(& if still no luck, feel free to send the schema.pl file over to Larry Gall or me)

**Comment by atalec** [comment]
We decided to just transfer and send the schema.pl file to Larry Gall.
